//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourOperator.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DreamTourEntities : DbContext
    {
        public DreamTourEntities()
            : base("name=DreamTourEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SystemUser> SystemUsers { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<Accommodation> Accommodations { get; set; }
        public virtual DbSet<Custom_Built> Custom_Builts { get; set; }
        public virtual DbSet<Default> Defaults { get; set; }
        public virtual DbSet<Tourist> Tourists { get; set; }
        public virtual DbSet<Administration> Administrations { get; set; }
    }
}
